name: Mira

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Unzip Project
      run: |
        unzip VoiceAssistant.zip -d extracted_app
        find extracted_app -name "build.gradle*"

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      run: |
        PROJ_DIR=$(dirname $(find extracted_app -name "gradlew" | head -n 1))
        cd "$PROJ_DIR"
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: VoiceAssistant-APK
        path: '**/build/outputs/apk/debug/*.apk'
